### ISSUE TITLE
Incorrect letter color

### ISSUE THREAD

**Issue by j-aarush** [6zs/hottle#1]
When I played todays warmle, I found a bug. The first z in pzazz should also be yellow
![IMG_1712](https://user-images.githubusercontent.com/104843813/166468696-a5d418d7-269c-4cf3-9b01-edeb7ba41fe8.jpeg)
.

**Comment by 6zs** [comment]
i think that's right -- in warmle the colors only tell you about *that* position, it's gray because Z isn't within 3 letters of I.
